import React, { useState, useRef } from 'react';
import { motion } from 'motion/react';
import { 
  Scissors, Upload, Sparkles, CheckCircle, ArrowRight, User, 
  Store, Palette, Image as ImageIcon, Sparkle, RefreshCw,
  Download, Database, AlertCircle
} from 'lucide-react';
import { ShopAccount } from '../types';
import { exportShopData, importShopBackup } from '../db';


interface BrandingSetupProps {
  currentShop: ShopAccount;
  onSave: (brandingData: { shopName: string; fullName: string; shopLogo: string }) => void;
  onCancel?: () => void;
}

const PRESET_LOGOS = [
  { id: 'logo-scissors', icon: 'Scissors', color: 'bg-emerald-800 text-amber-300 border-amber-300' },
  { id: 'logo-crown', icon: 'Crown', color: 'bg-amber-500 text-slate-900 border-amber-200' },
  { id: 'logo-suit', icon: 'Suit', color: 'bg-slate-900 text-amber-400 border-slate-800' },
  { id: 'logo-needle', icon: 'Needle', color: 'bg-indigo-900 text-pink-300 border-indigo-700' },
];

export default function BrandingSetup({ currentShop, onSave, onCancel }: BrandingSetupProps) {
  const [shopName, setShopName] = useState(currentShop.shopName || '');
  const [fullName, setFullName] = useState(currentShop.fullName || '');
  const [shopLogo, setShopLogo] = useState<string>(currentShop.shopLogo || '');
  const [selectedPreset, setSelectedPreset] = useState<string>('');
  const [dragActive, setDragActive] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const fileImportRef = useRef<HTMLInputElement>(null);

  const [importError, setImportError] = useState<string | null>(null);
  const [importSuccess, setImportSuccess] = useState<string | null>(null);
  const [showMergeDialog, setShowMergeDialog] = useState(false);
  const [pendingBackupStr, setPendingBackupStr] = useState('');

  const handleExportData = () => {
    try {
      const dataStr = exportShopData(currentShop.email);
      const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
      const exportFileDefaultName = `darzi_ledger_backup_${currentShop.shopName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.json`;
      
      const linkElement = document.createElement('a');
      linkElement.setAttribute('href', dataUri);
      linkElement.setAttribute('download', exportFileDefaultName);
      linkElement.click();
      setImportSuccess('Data exported successfully! Save this backup file securely on your device.');
      setImportError(null);
    } catch (e: any) {
      setImportError(e.message || 'Export failed');
      setImportSuccess(null);
    }
  };

  const handleFileImportSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const reader = new FileReader();
      reader.onload = (event) => {
        if (event.target?.result) {
          const content = event.target.result as string;
          try {
            const parsed = JSON.parse(content);
            if (!parsed || parsed.backupType !== 'darzi_ledger_backup') {
              setImportError('Invalid backup file. This file was not generated by Darzi Ledger.');
              setImportSuccess(null);
              return;
            }
            if (parsed.shopEmail.toLowerCase() !== currentShop.email.toLowerCase()) {
              setImportError(`Account mismatch. This backup belongs to "${parsed.shopEmail}", but you are logged in as "${currentShop.email}". One user's backup must never be imported into another user's account.`);
              setImportSuccess(null);
              return;
            }

            setPendingBackupStr(content);
            setShowMergeDialog(true);
            setImportError(null);
            setImportSuccess(null);
          } catch (err: any) {
            setImportError('Corrupted or invalid JSON backup file.');
            setImportSuccess(null);
          }
        }
      };
      reader.readAsText(file);
    }
  };

  const handleExecuteImport = (mode: 'merge' | 'replace') => {
    try {
      const result = importShopBackup(pendingBackupStr, mode, currentShop.email);
      if (result.success) {
        setImportSuccess('Backup restored successfully! All customer information, measurements, and order history have been updated. Refreshing register...');
        setImportError(null);
        setShowMergeDialog(false);
        setPendingBackupStr('');
        setTimeout(() => {
          window.location.reload();
        }, 1500);
      }
    } catch (e: any) {
      setImportError(e.message || 'Failed to restore backup.');
      setImportSuccess(null);
      setShowMergeDialog(false);
    }
  };


  // Helper to read and convert file to Base64
  const handleFile = (file: File) => {
    if (!file.type.startsWith('image/')) {
      setError('Please upload an image file (PNG, JPG, SVG, WEBP).');
      return;
    }
    if (file.size > 2 * 1024 * 1024) {
      setError('Image file size should be less than 2MB.');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      if (e.target?.result) {
        setShopLogo(e.target.result as string);
        setSelectedPreset('');
        setError(null);
      }
    };
    reader.readAsDataURL(file);
  };

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      handleFile(e.target.files[0]);
    }
  };

  const selectPreset = (preset: typeof PRESET_LOGOS[0]) => {
    setSelectedPreset(preset.id);
    // Store as preset-indicator
    setShopLogo(`PRESET:${preset.id}:${preset.color}`);
    setError(null);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!shopName.trim()) {
      setError('Shop Name is required.');
      return;
    }
    onSave({
      shopName: shopName.trim(),
      fullName: fullName.trim(),
      shopLogo
    });
  };

  // Helper to render the actual logo preview
  const renderLogoPreview = () => {
    if (!shopLogo) {
      return (
        <div className="w-16 h-16 bg-slate-100 border-2 border-dashed border-slate-300 rounded-full flex items-center justify-center text-slate-400 font-display font-bold text-lg">
          {shopName ? shopName.substring(0, 2).toUpperCase() : 'DL'}
        </div>
      );
    }

    if (shopLogo.startsWith('PRESET:')) {
      const parts = shopLogo.split(':');
      const iconType = parts[1];
      const colorClass = parts[2] || 'bg-emerald-800 text-amber-300 border-amber-300';
      return (
        <div className={`w-16 h-16 rounded-full flex items-center justify-center border font-display font-bold text-lg shadow-md ${colorClass}`}>
          {iconType === 'logo-scissors' && <Scissors className="w-7 h-7 rotate-90" />}
          {iconType === 'logo-crown' && <span className="text-xl">👑</span>}
          {iconType === 'logo-suit' && <span className="text-xl">👔</span>}
          {iconType === 'logo-needle' && <span className="text-xl">🪡</span>}
        </div>
      );
    }

    return (
      <img 
        src={shopLogo} 
        alt="Shop logo preview" 
        referrerPolicy="no-referrer"
        className="w-16 h-16 rounded-full object-cover border-2 border-emerald-600 shadow-md"
      />
    );
  };

  return (
    <div className="min-h-screen flex flex-col justify-center bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 relative overflow-hidden" id="branding-setup-container">
      {/* Decorative Blur Spheres */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-emerald-100 rounded-full mix-blend-multiply filter blur-3xl opacity-30 -mr-20 -mt-20"></div>
      <div className="absolute bottom-0 left-0 w-96 h-96 bg-amber-100 rounded-full mix-blend-multiply filter blur-3xl opacity-30 -ml-20 -mb-20"></div>

      <motion.div 
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-md w-full mx-auto"
        id="branding-setup-card-wrapper"
      >
        <div className="text-center mb-6" id="branding-setup-logo">
          <div className="inline-flex p-4 bg-emerald-800 text-amber-400 rounded-full shadow-lg border border-amber-300 items-center justify-center mb-4">
            <Sparkle className="w-8 h-8 animate-pulse text-amber-300" />
          </div>
          <h2 className="text-3xl font-bold font-display text-slate-900 tracking-tight">
            Configure Your Shop Brand
          </h2>
          <p className="mt-2 text-xs text-slate-500 max-w-sm mx-auto">
            Welcome to Darzi Ledger! Let's personalize the registry with your boutique's name, manager name, and a unique shop logo.
          </p>
        </div>

        <div className="bg-white shadow-xl rounded-2xl border border-slate-100 overflow-hidden relative z-10" id="branding-setup-form-box">
          <div className="bg-emerald-900/5 px-6 py-4 border-b border-slate-100 flex items-center justify-between">
            <span className="text-xxs font-bold text-emerald-800 uppercase tracking-wider">Premium Branding Setup</span>
            <span className="text-xxs text-slate-400 font-mono">Step 1 of 1</span>
          </div>

          <form onSubmit={handleSubmit} className="p-6 space-y-5" id="branding-setup-form">
            {error && (
              <div className="p-3 bg-rose-50 border-l-4 border-rose-500 text-rose-700 text-xs rounded flex items-start gap-2" id="branding-setup-error">
                <span>{error}</span>
              </div>
            )}

            {/* Shop Name Field */}
            <div>
              <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1 flex items-center gap-1">
                <Store className="w-3.5 h-3.5 text-emerald-800" />
                <span>Shop Name <span className="text-rose-500">*</span></span>
              </label>
              <input
                type="text"
                required
                value={shopName}
                onChange={(e) => setShopName(e.target.value)}
                placeholder="e.g. Al-Noor Royal Tailors"
                className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                id="setup-shop-name"
              />
            </div>

            {/* Owner Name Field */}
            <div>
              <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1 flex items-center gap-1">
                <User className="w-3.5 h-3.5 text-emerald-800" />
                <span>Owner / Manager Name <span className="text-slate-400 font-normal">(Optional)</span></span>
              </label>
              <input
                type="text"
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                placeholder="e.g. Mohammad Bilal"
                className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                id="setup-owner-name"
              />
            </div>

            {/* Shop Logo Field */}
            <div>
              <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-1">
                <Palette className="w-3.5 h-3.5 text-emerald-800" />
                <span>Shop Logo <span className="text-slate-400 font-normal">(Optional)</span></span>
              </label>

              <div className="flex items-center gap-4 mb-4" id="setup-logo-preview-row">
                {renderLogoPreview()}
                <div className="text-xxs text-slate-400 leading-normal">
                  <p className="font-bold text-slate-600">Your Brand Mark</p>
                  <p>Choose a monogram preset below, or drag & drop your custom shop emblem image.</p>
                </div>
              </div>

              {/* Preset selectors */}
              <div className="space-y-2 mb-4" id="setup-presets-area">
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Select Premium Monogram</p>
                <div className="grid grid-cols-4 gap-2">
                  {PRESET_LOGOS.map((preset) => (
                    <button
                      key={preset.id}
                      type="button"
                      onClick={() => selectPreset(preset)}
                      className={`py-2 rounded-xl border flex flex-col items-center justify-center transition-all ${
                        selectedPreset === preset.id
                          ? 'bg-emerald-50 border-emerald-600 ring-2 ring-emerald-600/10'
                          : 'bg-white border-slate-200 hover:bg-slate-50 hover:border-slate-300'
                      }`}
                    >
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm border font-bold ${preset.color}`}>
                        {preset.icon === 'Scissors' && <Scissors className="w-4 h-4 rotate-90" />}
                        {preset.icon === 'Crown' && '👑'}
                        {preset.icon === 'Suit' && '👔'}
                        {preset.icon === 'Needle' && '🪡'}
                      </div>
                      <span className="text-[9px] font-bold text-slate-500 mt-1 uppercase tracking-tighter">
                        {preset.icon}
                      </span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Drag-and-drop Image Area */}
              <div
                onDragEnter={handleDrag}
                onDragOver={handleDrag}
                onDragLeave={handleDrag}
                onDrop={handleDrop}
                onClick={() => fileInputRef.current?.click()}
                className={`border-2 border-dashed rounded-xl p-4 text-center cursor-pointer transition-all flex flex-col items-center justify-center gap-1.5 ${
                  dragActive 
                    ? 'border-emerald-600 bg-emerald-50/50' 
                    : 'border-slate-200 bg-slate-50 hover:bg-slate-100/50 hover:border-slate-300'
                }`}
                id="logo-dropzone"
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleFileSelect}
                  className="hidden"
                />
                <Upload className="w-5 h-5 text-slate-400" />
                <span className="text-xxs font-bold text-slate-600">
                  Drag & Drop Shop Logo Image or <span className="text-emerald-800 underline">Browse files</span>
                </span>
                <span className="text-[10px] text-slate-400">Supports PNG, JPG, SVG, WEBP up to 2MB</span>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-2.5 mt-4" id="setup-actions">
              {onCancel && (
                <button
                  type="button"
                  onClick={onCancel}
                  className="flex-1 bg-slate-100 hover:bg-slate-200 text-slate-700 font-display font-semibold rounded-xl py-3 px-4 transition-all active:scale-[0.98] text-xs text-center border border-slate-200"
                  id="setup-cancel-btn"
                >
                  Cancel
                </button>
              )}
              <button
                type="submit"
                className={`font-display font-semibold rounded-xl py-3 px-4 shadow-md transition-all active:scale-[0.98] flex items-center justify-center gap-2 text-xs ${
                  onCancel ? 'flex-[2] bg-emerald-800 hover:bg-emerald-900 text-amber-300' : 'w-full bg-emerald-800 hover:bg-emerald-900 text-amber-300'
                }`}
                id="setup-submit-btn"
              >
                <span>{onCancel ? 'Save Changes' : 'Save & Launch Register'}</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </form>
        </div>

        {/* Backup & Restore Card */}
        {onCancel && (
          <div className="bg-white shadow-xl rounded-2xl border border-slate-100 overflow-hidden mt-6 relative z-10" id="backup-restore-card">
            <div className="bg-slate-50 px-6 py-4 border-b border-slate-100 flex items-center justify-between">
              <span className="text-xxs font-bold text-slate-600 uppercase tracking-wider">Backup & Restore System</span>
              <span className="text-xxs text-amber-600 font-mono font-bold uppercase">Data Protection</span>
            </div>

            <div className="p-6 space-y-4">
              <p className="text-xxs text-slate-500 font-medium leading-relaxed">
                Export all customer records, measurements, order history, and pricing settings into a single secure file. You can restore this data at any time.
              </p>

              {importError && (
                <div className="p-3 bg-rose-50 border-l-4 border-rose-500 text-rose-700 text-xs rounded flex items-start gap-2" id="import-error-alert">
                  <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
                  <span>{importError}</span>
                </div>
              )}

              {importSuccess && (
                <div className="p-3 bg-emerald-50 border-l-4 border-emerald-500 text-emerald-700 text-xs rounded flex items-start gap-2" id="import-success-alert">
                  <CheckCircle className="w-4 h-4 shrink-0 mt-0.5" />
                  <span>{importSuccess}</span>
                </div>
              )}

              {/* Merge/Replace Modal overlay / Inline block */}
              {showMergeDialog && (
                <div className="p-4 bg-amber-50 rounded-xl border border-amber-200 space-y-3" id="merge-options-panel">
                  <div className="flex gap-2">
                    <Database className="w-4 h-4 text-amber-700 shrink-0 mt-0.5" />
                    <div>
                      <p className="text-xs font-bold text-slate-800">Choose Restore Method</p>
                      <p className="text-[11px] text-slate-600">You have existing data. How should the backup be applied?</p>
                    </div>
                  </div>
                  <div className="flex flex-col gap-2 pt-1">
                    <button
                      type="button"
                      onClick={() => handleExecuteImport('merge')}
                      className="w-full text-center py-2 bg-amber-500 hover:bg-amber-600 text-slate-900 font-bold rounded-lg shadow text-xs transition-all active:scale-95"
                    >
                      Merge (Keep Current Data & Import New)
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        if (window.confirm("WARNING: This will permanently delete your current local customer records and replace them with the backup data. This action cannot be undone. Proceed?")) {
                          handleExecuteImport('replace');
                        }
                      }}
                      className="w-full text-center py-2 bg-rose-600 hover:bg-rose-700 text-white font-bold rounded-lg shadow text-xs transition-all active:scale-95"
                    >
                      Replace (Overwrite Existing Data completely)
                    </button>
                    <button
                      type="button"
                      onClick={() => { setShowMergeDialog(false); setPendingBackupStr(''); }}
                      className="w-full text-center py-2 bg-slate-200 hover:bg-slate-300 text-slate-700 font-bold rounded-lg text-xs transition-all"
                    >
                      Cancel Restore
                    </button>
                  </div>
                </div>
              )}

              {!showMergeDialog && (
                <div className="grid grid-cols-2 gap-3" id="backup-action-buttons">
                  {/* Export Trigger */}
                  <button
                    type="button"
                    onClick={handleExportData}
                    className="flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-900 text-amber-300 font-semibold py-3 px-4 rounded-xl shadow transition-all active:scale-95 text-xs"
                    id="export-backup-btn"
                  >
                    <Download className="w-4 h-4" />
                    <span>Export Data</span>
                  </button>

                  {/* Import Trigger */}
                  <button
                    type="button"
                    onClick={() => fileImportRef.current?.click()}
                    className="flex items-center justify-center gap-2 bg-emerald-800 hover:bg-emerald-900 text-amber-300 font-semibold py-3 px-4 rounded-xl shadow transition-all active:scale-95 text-xs"
                    id="import-backup-btn"
                  >
                    <Upload className="w-4 h-4" />
                    <span>Import Backup</span>
                  </button>
                </div>
              )}

              <input
                ref={fileImportRef}
                type="file"
                accept=".json"
                onChange={handleFileImportSelect}
                className="hidden"
              />
            </div>
          </div>
        )}

        <div className="text-center mt-6 text-xs text-slate-400" id="branding-setup-footer">
          You can modify your branding logo and shop name at any time.
        </div>
      </motion.div>
    </div>
  );
}

