import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Scissors, KeyRound, Mail, AlertCircle, ShieldAlert, 
  Store, User, Phone, CheckCircle2, Coins, Clock, ArrowRight, HelpCircle,
  Upload, Database
} from 'lucide-react';
import { getShops, addShop, loginUser, updateShop, getBrowserDeviceId, importShopBackup } from '../db';
import { ShopAccount } from '../types';


interface LoginProps {
  onLoginSuccess: (email: string) => void;
}

export default function Login({ onLoginSuccess }: LoginProps) {
  const [activeTab, setActiveTab] = useState<'login' | 'signup'>('login');
  
  // Login State
  const [email, setEmail] = useState('tailor@darzi.pk');
  const [password, setPassword] = useState('darzi123');
  
  // Signup State
  const [signupShopName, setSignupShopName] = useState('');
  const [signupFullName, setSignupFullName] = useState('');
  const [signupMobile, setSignupMobile] = useState('');
  const [signupEmail, setSignupEmail] = useState('');
  const [signupPassword, setSignupPassword] = useState('');

  // Barrier / Feedback state for pending/suspended/expired accounts
  const [blockedAccount, setBlockedAccount] = useState<ShopAccount | null>(null);

  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // Backup & Import on Login Page States
  const fileImportRef = useRef<HTMLInputElement>(null);
  const [pendingBackupStr, setPendingBackupStr] = useState('');
  const [showPasswordPrompt, setShowPasswordPrompt] = useState(false);
  const [backupEmail, setBackupEmail] = useState('');
  const [backupPasswordInput, setBackupPasswordInput] = useState('');
  const [showLoginMergeDialog, setShowLoginMergeDialog] = useState(false);


  // Helper to open WhatsApp to Admin (Huzaifa)
  const contactAdminWhatsApp = (shopNameVal: string, emailVal: string, requestType: string) => {
    const textMessage = `Assalam-o-Alaikum Huzaifa! I want to ${requestType} my Darzi Ledger subscription.\n\nShop Name: ${shopNameVal}\nManager Email: ${emailVal}`;
    const encoded = encodeURIComponent(textMessage);
    window.open(`https://wa.me/923011163300?text=${encoded}`, '_blank');
  };

  const handleBackupFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const reader = new FileReader();
      reader.onload = (event) => {
        if (event.target?.result) {
          const content = event.target.result as string;
          try {
            const parsed = JSON.parse(content);
            if (!parsed || parsed.backupType !== 'darzi_ledger_backup') {
              setError('Invalid backup file. This file was not generated by Darzi Ledger.');
              setSuccess(null);
              return;
            }
            if (!parsed.shopEmail || !parsed.shop) {
              setError('Invalid backup data structure. Shop details are missing.');
              setSuccess(null);
              return;
            }

            setPendingBackupStr(content);
            setBackupEmail(parsed.shopEmail);
            setShowPasswordPrompt(true);
            setBackupPasswordInput('');
            setError(null);
            setSuccess(null);
          } catch (err) {
            setError('Corrupted or invalid JSON backup file.');
            setSuccess(null);
          }
        }
      };
      reader.readAsText(file);
    }
  };

  const handleVerifyBackupPassword = (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const parsed = JSON.parse(pendingBackupStr);
      const correctPassword = parsed.shop.password;
      
      if (backupPasswordInput !== correctPassword) {
        setError('Incorrect password for the backup account. Please enter the correct password.');
        setSuccess(null);
        return;
      }

      setShowPasswordPrompt(false);
      setShowLoginMergeDialog(true);
      setError(null);
    } catch (err) {
      setError('An error occurred during verification.');
      setShowPasswordPrompt(false);
    }
  };

  const handleExecuteLoginImport = (mode: 'merge' | 'replace') => {
    try {
      const result = importShopBackup(pendingBackupStr, mode);
      if (result.success) {
        setSuccess(`Backup verified! All data for "${result.email}" has been restored. Logging in...`);
        setError(null);
        setShowLoginMergeDialog(false);
        setPendingBackupStr('');
        
        setTimeout(() => {
          onLoginSuccess(result.email);
        }, 1500);
      }
    } catch (err: any) {
      setError(err.message || 'Import failed.');
      setSuccess(null);
      setShowLoginMergeDialog(false);
    }
  };


  const handleLoginSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    setBlockedAccount(null);

    setTimeout(() => {
      const inputVal = email.trim().toLowerCase();
      
      // 1. Super Admin authentication
      if (inputVal === 'huzaifa' || inputVal === 'huzaifa@darzi.pk') {
        if (password === 'Huzaifa2.107') {
          onLoginSuccess('Huzaifa');
          setIsLoading(false);
          return;
        } else {
          setError('Incorrect Super Admin password. (Hint: Huzaifa2.107)');
          setIsLoading(false);
          return;
        }
      }

      // 2. Regular shop user authentication
      const shops = getShops();
      const shop = shops.find(s => s.email.toLowerCase() === inputVal);
      
      if (shop) {
        if (shop.password === password || password === 'darzi123') { // Fallback standard password
          // One Device Security Check
          const currentDeviceId = getBrowserDeviceId();
          if (!shop.deviceId) {
            // Lock account to first-login device ID
            shop.deviceId = currentDeviceId;
            updateShop(shop.id, { deviceId: currentDeviceId });
          } else if (shop.deviceId !== currentDeviceId) {
            setError("Account already active on another device. Admin approval required for device change.");
            setIsLoading(false);
            return;
          }

          if (shop.status === 'Active') {
            onLoginSuccess(shop.email);
          } else {
            // Display subscription / status lock barrier
            setBlockedAccount(shop);
          }
        } else {
          setError('Invalid password for this shop register. (Hint: darzi123)');
        }
      } else {
        setError('No active shop found with this email. (Hint: Use default "tailor@darzi.pk" or register your shop)');
      }
      setIsLoading(false);
    }, 600);
  };

  const handleSignupSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    setSuccess(null);

    setTimeout(() => {
      const emailInput = signupEmail.trim().toLowerCase();
      
      if (!signupShopName.trim() || !signupFullName.trim() || !signupMobile.trim() || !signupEmail.trim() || !signupPassword.trim()) {
        setError('All sign-up fields are required.');
        setIsLoading(false);
        return;
      }

      const shops = getShops();
      const emailExists = shops.some(s => s.email.toLowerCase() === emailInput);
      if (emailExists || emailInput === 'huzaifa@darzi.pk' || emailInput === 'huzaifa') {
        setError('A shop account with this email address is already registered.');
        setIsLoading(false);
        return;
      }

      // Register shop - addShop will handle Active status and 3 Days Free Trial automatically
      const newShop = addShop({
        shopName: signupShopName.trim(),
        fullName: signupFullName.trim(),
        mobileNumber: signupMobile.trim(),
        email: signupEmail.trim(),
        password: signupPassword,
        status: 'Active',
        plan: 'Free Trial'
      });

      // Lock newly registered account to current device immediately
      const currentDeviceId = getBrowserDeviceId();
      updateShop(newShop.id, { deviceId: currentDeviceId });

      onLoginSuccess(newShop.email);
      setSuccess('Account created successfully! Your 3-day free trial starts now.');
      setIsLoading(false);

      // Clear fields
      setSignupShopName('');
      setSignupFullName('');
      setSignupMobile('');
      setSignupEmail('');
      setSignupPassword('');
    }, 600);
  };

  return (
    <div className="min-h-screen flex flex-col justify-center bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 relative overflow-hidden" id="login-container">
      {/* Absolute Decorative Motifs */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-emerald-100 rounded-full mix-blend-multiply filter blur-3xl opacity-30 -mr-20 -mt-20"></div>
      <div className="absolute bottom-0 left-0 w-96 h-96 bg-amber-100 rounded-full mix-blend-multiply filter blur-3xl opacity-30 -ml-20 -mb-20"></div>

      <motion.div 
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-md w-full mx-auto"
        id="login-card-wrapper"
      >
        <div className="flex justify-center mb-5" id="login-logo-container">
          <div className="p-4 bg-emerald-800 text-amber-400 rounded-full shadow-lg border border-amber-300 flex items-center justify-center">
            <Scissors className="w-8 h-8 rotate-90" />
          </div>
        </div>

        <div className="text-center mb-6" id="login-header-text">
          <h2 className="text-3xl font-bold font-display text-slate-900 tracking-tight">
            Darzi Ledger
          </h2>
          <p className="mt-1 text-xs text-slate-500">
            Premium Tailoring Shop Register & Measurements Book
          </p>
        </div>

        {/* Dynamic Barrier / Account Status Locking State */}
        <AnimatePresence mode="wait">
          {blockedAccount ? (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white p-6 shadow-xl rounded-2xl border border-rose-100 relative z-10 space-y-6"
              id="login-blocked-barrier"
            >
              {/* Custom Status Display */}
              {blockedAccount.status === 'Pending Approval' && (
                <div className="text-center space-y-3" id="barrier-pending">
                  <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-full flex items-center justify-center mx-auto border border-amber-100">
                    <Clock className="w-6 h-6" />
                  </div>
                  <div className="space-y-1">
                    <span className="inline-block text-[10px] font-bold tracking-wider uppercase bg-amber-100 text-amber-800 px-2.5 py-0.5 rounded-full">
                      Pending Approval
                    </span>
                    <h3 className="text-lg font-bold text-slate-800 font-display">Account Under Review</h3>
                    <p className="text-xs text-slate-500 font-medium leading-relaxed px-4">
                      Please contact admin to activate your subscription.
                    </p>
                  </div>
                </div>
              )}

              {blockedAccount.status === 'Expired' && (
                <div className="text-center space-y-3" id="barrier-expired">
                  <div className="w-12 h-12 bg-rose-50 text-rose-600 rounded-full flex items-center justify-center mx-auto border border-rose-100">
                    <ShieldAlert className="w-6 h-6" />
                  </div>
                  <div className="space-y-1">
                    <span className="inline-block text-[10px] font-bold tracking-wider uppercase bg-rose-100 text-rose-800 px-2.5 py-0.5 rounded-full">
                      Free Trial Expired
                    </span>
                    <h3 className="text-lg font-bold text-slate-800 font-display">Service Suspended</h3>
                    <p className="text-xs text-rose-700 font-semibold leading-relaxed px-4">
                      Your 3-day free trial has expired. Please contact admin to activate a plan.
                    </p>
                  </div>
                </div>
              )}

              {blockedAccount.status === 'Suspended' && (
                <div className="text-center space-y-3" id="barrier-suspended">
                  <div className="w-12 h-12 bg-red-100 text-red-700 rounded-full flex items-center justify-center mx-auto border border-red-200">
                    <AlertCircle className="w-6 h-6 animate-pulse" />
                  </div>
                  <div className="space-y-1">
                    <span className="inline-block text-[10px] font-bold tracking-wider uppercase bg-red-200 text-red-800 px-2.5 py-0.5 rounded-full">
                      Account Suspended
                    </span>
                    <h3 className="text-lg font-bold text-slate-800 font-display">Access Prohibited</h3>
                    <p className="text-xs text-slate-500 font-medium leading-relaxed px-4">
                      Your account has been suspended. Contact admin.
                    </p>
                  </div>
                </div>
              )}

              {/* Buy Subscription Page Details integrated here for locked users */}
              <div className="bg-slate-50 rounded-xl p-4 border border-slate-100 space-y-3.5" id="barrier-pricing">
                <div className="flex items-center justify-between border-b border-slate-200/60 pb-2">
                  <h4 className="text-xs font-bold text-slate-700 font-display uppercase tracking-wider">Buy Subscription</h4>
                  <span className="text-[10px] text-slate-400 font-medium">Premium Digital Ledger</span>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  {/* Monthly Price Card */}
                  <div className="bg-white border border-slate-100 p-3 rounded-lg text-center space-y-1">
                    <div className="flex justify-center text-blue-600 mb-0.5">
                      <Clock className="w-4 h-4" />
                    </div>
                    <p className="text-[10px] font-bold text-slate-400 uppercase">Monthly Plan</p>
                    <p className="text-sm font-bold text-slate-800">Rs. 1,500 <span className="text-[9px] text-slate-400 font-normal">/mo</span></p>
                  </div>

                  {/* Lifetime Price Card */}
                  <div className="bg-white border border-slate-100 p-3 rounded-lg text-center space-y-1">
                    <div className="flex justify-center text-amber-500 mb-0.5">
                      <Coins className="w-4 h-4" />
                    </div>
                    <p className="text-[10px] font-bold text-slate-400 uppercase">Lifetime Plan</p>
                    <p className="text-sm font-bold text-slate-800">Rs. 12,000 <span className="text-[9px] text-slate-400 font-normal">once</span></p>
                  </div>
                </div>

                {/* Contact Admin WhatsApp Call-to-Action */}
                <button
                  onClick={() => contactAdminWhatsApp(
                    blockedAccount.shopName, 
                    blockedAccount.email, 
                    blockedAccount.status === 'Pending Approval' ? 'activate' : 'renew'
                  )}
                  className="w-full flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-display font-semibold text-xs py-2.5 px-4 rounded-xl shadow-md transition-all active:scale-95"
                  id="barrier-whatsapp-btn"
                >
                  <Phone className="w-4 h-4" />
                  <span>Contact Admin on WhatsApp</span>
                </button>
              </div>

              {/* Exit/Back to Login Button */}
              <button
                onClick={() => {
                  setBlockedAccount(null);
                  setError(null);
                  setSuccess(null);
                  setActiveTab('login');
                }}
                className="w-full text-center text-xs font-semibold text-slate-500 hover:text-slate-800 transition-colors py-1 block"
                id="barrier-back-btn"
              >
                ← Back to Login Screen
              </button>
            </motion.div>
          ) : (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="bg-white shadow-xl rounded-2xl border border-slate-100 overflow-hidden relative z-10"
              id="login-form-box"
            >
              {/* Promo Banner for Free Trial */}
              <div className="bg-gradient-to-r from-emerald-800 to-emerald-700 text-amber-300 py-3 px-4 text-center text-xs font-bold flex items-center justify-center gap-1.5 border-b border-emerald-900" id="login-trial-promo">
                <span>🎉 3 Days Free Trial Available</span>
              </div>
              {/* Signup / Login Tab Selector */}
              <div className="flex border-b border-slate-100" id="login-tabs">
                <button
                  type="button"
                  onClick={() => {
                    setActiveTab('login');
                    setError(null);
                    setSuccess(null);
                  }}
                  className={`flex-1 text-center py-3.5 font-display text-xs font-bold transition-all ${
                    activeTab === 'login'
                      ? 'bg-white text-emerald-800 border-b-2 border-emerald-800'
                      : 'bg-slate-50/50 text-slate-400 hover:bg-slate-50'
                  }`}
                >
                  Sign In to Shop
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setActiveTab('signup');
                    setError(null);
                    setSuccess(null);
                  }}
                  className={`flex-1 text-center py-3.5 font-display text-xs font-bold transition-all ${
                    activeTab === 'signup'
                      ? 'bg-white text-emerald-800 border-b-2 border-emerald-800'
                      : 'bg-slate-50/50 text-slate-400 hover:bg-slate-50'
                  }`}
                >
                  Register New Shop
                </button>
              </div>

              <div className="p-6">
                {/* Error Banner */}
                {error && (
                  <motion.div 
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    className="mb-4 p-3 bg-red-50 border-l-4 border-red-500 text-red-700 text-xs rounded flex items-start gap-2"
                    id="login-error-msg"
                  >
                    <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                    <span>{error}</span>
                  </motion.div>
                )}

                {/* Success Banner */}
                {success && (
                  <motion.div 
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    className="mb-4 p-3 bg-emerald-50 border-l-4 border-emerald-500 text-emerald-800 text-xs rounded flex items-start gap-2"
                    id="login-success-msg"
                  >
                    <CheckCircle2 className="w-4 h-4 mt-0.5 shrink-0" />
                    <span>{success}</span>
                  </motion.div>
                )}

                {showPasswordPrompt ? (
                  /* PASSWORD PROMPT FOR IMPORT */
                  <form onSubmit={handleVerifyBackupPassword} className="space-y-4" id="backup-password-form">
                    <div className="p-3 bg-amber-50 rounded-xl border border-amber-100 flex items-start gap-2 text-xxs text-amber-800 font-medium mb-2">
                      <AlertCircle className="w-4 h-4 mt-0.5 shrink-0 animate-pulse" />
                      <div>
                        <p className="font-bold">Backup Account Detected: {backupEmail}</p>
                        <p className="mt-0.5">To protect your database privacy, please enter the account password to authorize restoration and sign in.</p>
                      </div>
                    </div>

                    <div>
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Security Password
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <KeyRound className="w-4 h-4" />
                        </div>
                        <input
                          type="password"
                          required
                          value={backupPasswordInput}
                          onChange={(e) => setBackupPasswordInput(e.target.value)}
                          placeholder="Enter account password"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={() => { setShowPasswordPrompt(false); setPendingBackupStr(''); }}
                        className="flex-1 bg-slate-100 hover:bg-slate-200 text-slate-600 font-semibold rounded-xl py-2 px-4 text-xs transition-all border border-slate-200"
                      >
                        Cancel
                      </button>
                      <button
                        type="submit"
                        className="flex-1 bg-emerald-800 hover:bg-emerald-900 text-amber-300 font-semibold rounded-xl py-2 px-4 text-xs shadow transition-all"
                      >
                        Verify & Continue
                      </button>
                    </div>
                  </form>
                ) : showLoginMergeDialog ? (
                  /* MERGE OR REPLACE CHOOSE FOR LOGIN IMPORT */
                  <div className="space-y-4" id="backup-merge-choice">
                    <div className="p-3.5 bg-emerald-50 rounded-xl border border-emerald-100 flex items-start gap-2 text-xxs text-emerald-800 font-medium">
                      <CheckCircle2 className="w-4 h-4 mt-0.5 shrink-0" />
                      <div>
                        <p className="font-bold">Password Verified!</p>
                        <p className="mt-0.5">Please choose how you would like to restore your database on this device:</p>
                      </div>
                    </div>

                    <div className="flex flex-col gap-2 pt-1">
                      <button
                        type="button"
                        onClick={() => handleExecuteLoginImport('merge')}
                        className="w-full text-center py-2.5 bg-amber-500 hover:bg-amber-600 text-slate-900 font-bold rounded-xl shadow text-xs transition-all active:scale-95"
                      >
                        Merge (Preserve current local data & add backup)
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          if (window.confirm("WARNING: This will overwrite any existing local records for this account with the backup data. Proceed?")) {
                            handleExecuteLoginImport('replace');
                          }
                        }}
                        className="w-full text-center py-2.5 bg-rose-600 hover:bg-rose-700 text-white font-bold rounded-xl shadow text-xs transition-all active:scale-95"
                      >
                        Replace (Overwrite with Backup completely)
                      </button>
                      <button
                        type="button"
                        onClick={() => { setShowLoginMergeDialog(false); setPendingBackupStr(''); }}
                        className="w-full text-center py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold rounded-xl text-xs transition-all border border-slate-200"
                      >
                        Cancel Restore
                      </button>
                    </div>
                  </div>
                ) : activeTab === 'login' ? (
                  /* LOGIN FORM */
                  <form onSubmit={handleLoginSubmit} className="space-y-4" id="login-form">
                    <div id="email-group">
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Email Address
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <Mail className="w-4 h-4" />
                        </div>
                        <input
                          id="login-email"
                          type="email"
                          required
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          placeholder="name@shop.com"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <div id="password-group">
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Password
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <KeyRound className="w-4 h-4" />
                        </div>
                        <input
                          id="login-password"
                          type="password"
                          required
                          value={password}
                          onChange={(e) => setPassword(e.target.value)}
                          placeholder="Enter shop password"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <div className="flex items-center justify-between text-xxs pt-1 text-slate-400" id="login-helper-links">
                      <div>
                        Default: <span className="font-mono text-emerald-800 bg-emerald-50 px-1 py-0.5 rounded font-bold">darzi123</span>
                      </div>
                      <span className="font-medium text-slate-400">Quick Access Verified</span>
                    </div>

                    <button
                      id="login-submit-btn"
                      type="submit"
                      disabled={isLoading}
                      className="w-full bg-emerald-800 hover:bg-emerald-900 text-amber-300 font-display font-semibold rounded-xl py-2.5 px-4 shadow-md transition-all active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 mt-2 text-xs"
                    >
                      {isLoading ? (
                        <div className="w-4 h-4 border-2 border-amber-300 border-t-transparent rounded-full animate-spin"></div>
                      ) : (
                        'Sign In to Register'
                      )}
                    </button>

                    <div className="relative flex py-2 items-center">
                      <div className="flex-grow border-t border-slate-100"></div>
                      <span className="flex-shrink mx-4 text-slate-400 text-[10px] uppercase font-bold tracking-wider">or restore data</span>
                      <div className="flex-grow border-t border-slate-100"></div>
                    </div>

                    <button
                      type="button"
                      onClick={() => fileImportRef.current?.click()}
                      className="w-full bg-slate-50 hover:bg-slate-100 text-slate-700 font-display font-semibold rounded-xl py-2.5 px-4 transition-all active:scale-[0.98] flex items-center justify-center gap-2 text-xs border border-slate-200"
                      id="login-import-backup-btn"
                    >
                      <Upload className="w-4 h-4 text-slate-500" />
                      <span>Import Backup File</span>
                    </button>

                    <input
                      ref={fileImportRef}
                      type="file"
                      accept=".json"
                      onChange={handleBackupFileSelect}
                      className="hidden"
                    />
                  </form>
                ) : (
                  /* SIGNUP FORM */
                  <form onSubmit={handleSignupSubmit} className="space-y-4" id="signup-form">
                    <div id="signup-shop-group">
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Shop Name
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <Store className="w-4 h-4" />
                        </div>
                        <input
                          type="text"
                          required
                          value={signupShopName}
                          onChange={(e) => setSignupShopName(e.target.value)}
                          placeholder="e.g. Al-Noor Royal Tailors"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <div id="signup-name-group">
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Full Name
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <User className="w-4 h-4" />
                        </div>
                        <input
                          type="text"
                          required
                          value={signupFullName}
                          onChange={(e) => setSignupFullName(e.target.value)}
                          placeholder="e.g. Mohammad Bilal"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <div id="signup-mobile-group">
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Mobile Number
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <Phone className="w-4 h-4" />
                        </div>
                        <input
                          type="tel"
                          required
                          value={signupMobile}
                          onChange={(e) => setSignupMobile(e.target.value)}
                          placeholder="e.g. 03001234567"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <div id="signup-email-group">
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Email Address
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <Mail className="w-4 h-4" />
                        </div>
                        <input
                          type="email"
                          required
                          value={signupEmail}
                          onChange={(e) => setSignupEmail(e.target.value)}
                          placeholder="name@shop.com"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <div id="signup-password-group">
                      <label className="block text-xxs font-bold uppercase tracking-wider text-slate-500 mb-1">
                        Security Password
                      </label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                          <KeyRound className="w-4 h-4" />
                        </div>
                        <input
                          type="password"
                          required
                          value={signupPassword}
                          onChange={(e) => setSignupPassword(e.target.value)}
                          placeholder="Choose password"
                          className="pl-10 w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 px-4 text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-emerald-700 focus:bg-white focus:ring-2 focus:ring-emerald-700/5 text-xs"
                        />
                      </div>
                    </div>

                    <button
                      type="submit"
                      disabled={isLoading}
                      className="w-full bg-emerald-800 hover:bg-emerald-900 text-amber-300 font-display font-semibold rounded-xl py-2.5 px-4 shadow-md transition-all active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 mt-2 text-xs"
                    >
                      {isLoading ? (
                        <div className="w-4 h-4 border-2 border-amber-300 border-t-transparent rounded-full animate-spin"></div>
                      ) : (
                        'Submit Registration'
                      )}
                    </button>
                  </form>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="text-center mt-6 text-xs text-slate-400" id="login-footer">
          Darzi Ledger v1.0.0 • Mobile-First Shop Register
        </div>
      </motion.div>
    </div>
  );
}
